workflows:
  ios-simulator:
    name: Build iOS simulator app
    environment:
      flutter: latest
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build iOS simulator app
        script: |
          flutter build ios --simulator --release
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app

    artifacts:
      - build/ios/iphonesimulator/Runner.app.zip
